language: python
python:
  - '3.5'
  - '3.6'
install:
  - pip3 install -r requirements.txt
script:
  - python3 -m flake8
  - python3 -m pytest
  - coveralls
deploy:
  provider: pypi
  user: tomkukral
  password:
    secure: O3tVh0xFjXcJYciCLsEASJIipWa68W9OOGMg/YMYTRFclL8IY52dq6+lJbcpNnKlozKr8aR146FfcUKreKB1bdS3FpcVb/wYf/zOFeoVEeB+XKXJlsn9ohhJ5chiujQnhinyyxCbEXoYw+Ae4geki5F2AkZonTf2Z8KMTonxcjJbIZXGbfZKMJ/KZbEN54Cec5s00GpvzNie7lh/XnvX5yVqt3yToC25ZiMlt11Fv7yYr02DQ5EFVGUONYsjE8Blm1NMFLs0Zj7dA1TqMAMbcTjDdXvUo195rC204/5CFRu0b8Irpnkd4lMaJe9L2FdLXyCYql+ODqscaCkEvHQ0yFYoPUmZSjFiHQUt5hKmbdPPWIcdg4hxi8hgVakYmZmF7zZRkOpddIVY/wAx6B9spU6eqs3uhMo6mP15SFSHfKVcEiDSFmnTT90LWVpdydC+F5lc7OsHzWG/RG9fSunsVTjEMcdzBYFOYnHOL3ewVmYQPqV7mpZTdEdhOtpAKZUVCsr6AS/2wiZznwIZMtQ45nXlh02IgLAtAc4OlwBN0sFThQ2vSkqBwscQtD5JTHfA82Jalx710ny4h1q9KIvTPP+tWPMZUoD6u8iBraRA96vMPpiMVcJQd71OFim6poyZOXCo9sXV/4chXwyydDWZ6h/bqUOzHbQ5hE/D/Eu5nIE=
  on:
    tags: true
    repo: tomkukral/kib
